// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");

Jest.describe("Test", (function (param) {
        Jest.test("toBe", (function (param) {
                return Jest.Expect[/* toBe */2](3, Jest.Expect[/* expect */0](3));
              }));
        Jest.test("not toBe", (function (param) {
                return Jest.Expect[/* toBe */2](4, Jest.Expect[/* not_ */23](Jest.Expect[/* expect */0](3)));
              }));
        return Jest.test("not_ toBe", (function (param) {
                      return Jest.Expect[/* toBe */2](4, Jest.Expect[/* not__ */24](Jest.Expect[/* expect */0](3)));
                    }));
      }));

/*  Not a pure module */
