// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Reductive = require("reductive/lib/js/src/reductive.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

function logger(store, next, action) {
  console.log(action);
  var returnValue = Curry._1(next, action);
  console.log(Reductive.Store[/* getState */5](store));
  return returnValue;
}

var Thunk = Caml_exceptions.create("Middleware.Thunk");

function thunk(store, next, action) {
  if (action[0] === Thunk) {
    var partial_arg = Reductive.Store[/* dispatch */4];
    return Curry._2(action[1], (function (param) {
                  return partial_arg(store, param);
                }), Reductive.Store[/* getState */5](store));
  } else {
    return Curry._1(next, action);
  }
}

exports.logger = logger;
exports.Thunk = Thunk;
exports.thunk = thunk;
/* Reductive Not a pure module */
