// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Reductive = require("reductive/lib/js/src/reductive.js");

function counter(state, action) {
  if (action) {
    return state - 1 | 0;
  } else {
    return state + 1 | 0;
  }
}

function doubleCounter(state, action) {
  if (action) {
    return state - 2 | 0;
  } else {
    return state + 2 | 0;
  }
}

var store = Reductive.Store[/* create */0](counter, 0, undefined, /* () */0);

exports.counter = counter;
exports.doubleCounter = doubleCounter;
exports.store = store;
/* store Not a pure module */
